### PR TITLE
Polyscope slicer and visualization of the ASO scalar field as example

### PR DESCRIPTION
**Pull request by dcoeurjo**
Add a generic (regular) slicer in polyscope.

Note that if openmp is activated, the implicit function evaluations are computed in //

Capture d’écran 2023-12-09 à 17 48 37

### CODE REVIEW

**Comment by nmellado** [comment]
Thanks, very nice !
There is something weird with the diff of `main.cpp`, did you change the encoding or something ?

**Comment by dcoeurjo** [comment]
Yep I saw that.. I didn't change the encoding, maybe my editor did but that's weird. I will try to revert to the original main.cpp with my edits

**Comment by dcoeurjo** [comment]
Ok I managed to get the main.cpp back.. Probably an encoding issue..

**Comment by nmellado** [comment]
Nice.
Do you think you could add the fit type as a template parameter in the slice generation method ?
Or we can leave that for a upcoming PR.

**Comment by dcoeurjo** [comment]
Do you mean the a template to the implicit function functor ? 
If so, it's the `Functor` typename in the `polyscopeSlicer.hpp`

**Comment by nmellado** [comment]
I mean `Scalar eval_scalar_field_ASO(const VectorType& input_pos)`

**Comment by dcoeurjo** [comment]
Oh I see, definitely agree...
In the `main.cpp`, the ASO is just an example here (from @ThibaultLejemble). This could definitely be improved with a collection of functors and a switch in the callback

**Comment by nmellado** [comment]
ok, we leave this for later ?

**Comment by dcoeurjo** [comment]
Up to you. I'm not enough skilled in Ponca templates to create the functors for all other implicits. 
If someone could do it, I'd be happy to update the Imgui callback accordingly

**Comment by nmellado** [comment]
ok, will try to have a look

**Comment by nmellado** [comment]
@dcoeurjo I pushed a commit that hopefully provides everything you need.

**Comment by dcoeurjo** [comment]
combo selector added.  @nmellado at this point ASO==APSS, right ?


Capture d’écran 2023-12-14 à 13 14 39

**Comment by nmellado** [comment]
For the distance fields yes. If we display the derivatives, the fields will be different.

**Comment by dcoeurjo** [comment]
Yes for the slicer

**Comment by dcoeurjo** [comment]
(any existing method to get the bounding box of the tree?)

**Comment by nmellado** [comment]
it's supposed to be soon in Ponca, let me check if it can be done now

**Comment by nmellado** [comment]
I've pushed a proposal to ease this process: https://github.com/poncateam/ponca/pull/128

**Comment by nmellado** [comment]
@dcoeurjo we can now access the aabb of the kdtree node. How do you want to use it ? I can show how to use it, but that would help to know how it will be used.

**Comment by dcoeurjo** [comment]
I was just looking for a way to get the bounding box of the point cloud. I could recompute it but I thought that the function may already exist in the tree API. 
This is very minor.

**Comment by nmellado** [comment]
It is not stored by default (to save memory space), but it can be added easily. So, as you prefer, maybe it is easier to keep the code simple an recompute it when loading the file.

**Comment by dcoeurjo** [comment]
No I'll do it by myself in the viewer.. no need to store extra data.

**Comment by nmellado** [comment]
ok, feel free to ping me when the PR is ready to be reviewed.

**Comment by dcoeurjo** [comment]
Ready ;)

**Review by nmellado — APPROVED** [review]
I did a small updates, feel free to amend/comment:
 -  better display with plane fit by forcing positive distances (avoid random sign swap)
 - add plane fit as mean normal/position.

Also, I see that there is a potential problem with APSS: the distance field requires to be normalized (using Pratt norm) if we want to compare it against other distance fields.

**Comment by nmellado** [comment]
(I just rebased the branch on top of `main`)

**Pull request merged**
